.PHONY: clean All

All:
	@echo "----------Building project:[ ACSAC - Debug ]----------"
	@cd "ACSAC" && "$(MAKE)" -f  "ACSAC.mk"
clean:
	@echo "----------Cleaning project:[ ACSAC - Debug ]----------"
	@cd "ACSAC" && "$(MAKE)" -f  "ACSAC.mk" clean
